# Generated by Django 5.0.5 on 2024-05-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0004_remove_additionalfree_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfree',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
