# Generated by Django 5.0.5 on 2024-05-09 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0005_alter_additionalfree_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_meat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_meat_bag', to='hamburgueria.additionalfree')),
                ('additional_sauce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_sauce_bag', to='hamburgueria.additionalfree')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bag', to='hamburgueria.products')),
            ],
        ),
    ]
