# Generated by Django 5.0.5 on 2024-05-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0006_bagproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagproduct',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
