# Generated by Django 5.0.5 on 2024-05-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0007_bagproduct_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagproduct',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
