# Generated by Django 5.0.5 on 2024-05-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0008_bagproduct_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagproduct',
            name='additional_meat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_meat_bag', to='hamburgueria.additionalfree'),
        ),
        migrations.AlterField(
            model_name='bagproduct',
            name='additional_sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_sauce_bag', to='hamburgueria.additionalfree'),
        ),
    ]
